const SS_FILES = [
  "Imagen12.png",
  "Imagen13.png",
  "Imagen14.jpg",
  "Imagen15.png",
  "Imagen16.png",
  "Imagen17.png",
  "Imagen18.png",
  "Imagen24.png",
  "Imagen25.png",
  "Imagen26.jpg",
  "Imagen27.png",
  "Imagen28.jpg",
  "Imagen29.jpg",
  "Imagen30.png",
  "Imagen31.png",
  "Imagen32.jpg",
  "Imagen33.jpg",
  "Imagen34.png",
  "Imagen35.png",
  "Imagen36.png",
  "Imagen37.jpg",
  "Imagen43.jpg",
  "Imagen44.jpg",
  "Imagen45.jpg",
  "ChatGPT Image 4 jun 2026, 09_18_44.png",
  "ChatGPT Image 4 jun 2026, 09_19_47.png",
  "ChatGPT Image 4 jun 2026, 09_20_49.png",
  "ChatGPT Image 4 jun 2026, 09_26_59.png",
  "ChatGPT Image 4 jun 2026, 09_28_14.png",
  "ChatGPT Image 4 jun 2026, 09_30_11.png",
  "ChatGPT Image 4 jun 2026, 09_31_27.png",
  "ChatGPT Image 4 jun 2026, 09_32_38.png",
  "ChatGPT Image 4 jun 2026, 09_33_53.png",
  "ChatGPT Image 4 jun 2026, 09_35_05.png",
] as const;

export const SS_GALLERY_IMAGES = SS_FILES.map(
  (file) => `/ss/${encodeURIComponent(file)}`
);

/** Subset destacado (8 imágenes) */
export const SS_GALLERY_FEATURED = [
  "Imagen43.jpg",
  "Imagen31.png",
  "Imagen27.png",
  "Imagen25.png",
  "ChatGPT Image 4 jun 2026, 09_28_14.png",
  "Imagen44.jpg",
  "Imagen15.png",
  "Imagen32.jpg",
].map((file) => `/ss/${encodeURIComponent(file)}`);

const carouselLabels: Record<string, string> = {
  "Imagen12.png": "Edificio tecnológico — data center y NOC",
  "Imagen13.png": "Switches y equipamiento de red",
  "Imagen14.jpg": "Obra civil — piso técnico y cableado",
  "Imagen15.png": "Detección de intrusión perimetral",
  "Imagen16.png": "Control de accesos con tarjeta",
  "Imagen17.png": "Cámara CCTV de seguridad",
  "Imagen18.png": "Lector de acceso biométrico",
  "Imagen24.png": "Tablero eléctrico de distribución",
  "Imagen25.png": "Cableado estructurado en rack",
  "Imagen26.jpg": "Grupo electrógeno Palmero en jaula",
  "Imagen27.png": "Bandejas portacables en data center",
  "Imagen28.jpg": "Instalación solar e inversores",
  "Imagen29.jpg": "Grupo electrógeno 30 KVA",
  "Imagen30.png": "Montaje de equipo con telehandler",
  "Imagen31.png": "Rack de servidores y UPS Eaton",
  "Imagen32.jpg": "Chillers industriales en azotea",
  "Imagen33.jpg": "Equipos HVAC Goodman",
  "Imagen34.png": "Condensadoras BGH en fachada",
  "Imagen35.png": "Mantenimiento de equipo técnico",
  "Imagen36.png": "HVAC en azotea con torre de comunicaciones",
  "Imagen37.jpg": "Refrigeración de precisión en sala técnica",
  "Imagen43.jpg": "Data center — pasillo de racks",
  "Imagen44.jpg": "Grupos electrógenos Caterpillar",
  "Imagen45.jpg": "Sistema de enfriamiento industrial",
  "ChatGPT Image 4 jun 2026, 09_18_44.png": "Cámara domo en rack de data center",
  "ChatGPT Image 4 jun 2026, 09_19_47.png": "Cámara PTZ de vigilancia",
  "ChatGPT Image 4 jun 2026, 09_20_49.png": "Sistema CCTV multipunto",
  "ChatGPT Image 4 jun 2026, 09_26_59.png": "Rack con cableado de red",
  "ChatGPT Image 4 jun 2026, 09_28_14.png": "Fusión de fibra óptica",
  "ChatGPT Image 4 jun 2026, 09_30_11.png": "Tablero Schneider Electric",
  "ChatGPT Image 4 jun 2026, 09_31_27.png": "Grupo electrógeno industrial",
  "ChatGPT Image 4 jun 2026, 09_32_38.png": "Condensadora YORK en azotea",
  "ChatGPT Image 4 jun 2026, 09_33_53.png": "Gabinete de red empresarial",
  "ChatGPT Image 4 jun 2026, 09_35_05.png": "Unidades VRF en cubierta",
};

/** Todas las fotos de public/ss para el carrusel 3D */
export const SS_GALLERY_CAROUSEL = SS_FILES.map((file) => ({
  src: `/ss/${encodeURIComponent(file)}`,
  alt: carouselLabels[file] ?? "Proyecto de infraestructura Green Working",
}));
